import { describe, expect, it } from "vitest";
import { createEmptyPermissionState } from "../../../src/permissions/types.js";
import type { JsonRpcRequest, MessageSendParams } from "../../../src/protocol/types.js";
import {
	DEFAULT_MESSAGE_SCOPE,
	buildOutgoingMessageRequest,
} from "../../../src/runtime/message-conversations.js";
import type { Contact } from "../../../src/trust/types.js";

const CONTACT: Contact = {
	connectionId: "conn-test-001",
	peerAgentId: 42,
	peerChain: "eip155:8453",
	peerOwnerAddress: "0x1111111111111111111111111111111111111111",
	peerDisplayName: "TestPeer",
	peerAgentAddress: "0x2222222222222222222222222222222222222222",
	permissions: createEmptyPermissionState("2026-01-01T00:00:00.000Z"),
	establishedAt: "2026-01-01T00:00:00.000Z",
	lastContactAt: "2026-01-01T00:00:00.000Z",
	status: "active",
};

function getAutoGenerated(request: JsonRpcRequest): boolean | undefined {
	const params = request.params as MessageSendParams;
	return params.message.metadata?.trustedAgent?.autoGenerated;
}

describe("autoGenerated flag in outgoing messages", () => {
	it.each([
		["not provided", "hello", undefined, undefined],
		["explicitly true", "auto reply", true, true],
		["explicitly false", "manual", false, undefined],
	] as const)("autoGenerated %s → %s", (_, text, input, expected) => {
		const request = buildOutgoingMessageRequest(
			CONTACT,
			text,
			DEFAULT_MESSAGE_SCOPE,
			input !== undefined ? { autoGenerated: input } : undefined,
		);
		expect(getAutoGenerated(request)).toBe(expected);
	});
});
