import { describe, expect, it } from "vitest";
import { createEmptyPermissionState } from "../../../src/permissions/types.js";
import {
	DEFAULT_MESSAGE_SCOPE,
	buildOutgoingMessageRequest,
} from "../../../src/runtime/message-conversations.js";
import type { Contact } from "../../../src/trust/types.js";

const CONTACT: Contact = {
	connectionId: "conn-test-001",
	peerAgentId: 42,
	peerChain: "eip155:84532",
	peerOwnerAddress: "0x1111111111111111111111111111111111111111",
	peerDisplayName: "TestPeer",
	peerAgentAddress: "0x2222222222222222222222222222222222222222",
	permissions: createEmptyPermissionState("2026-01-01T00:00:00.000Z"),
	establishedAt: "2026-01-01T00:00:00.000Z",
	lastContactAt: "2026-01-01T00:00:00.000Z",
	status: "active",
};

describe("autoGenerated flag in outgoing messages", () => {
	it("does not set autoGenerated when not provided", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "hello");
		const message = (
			request.params as {
				message: { metadata: { trustedAgent: { autoGenerated?: boolean } } };
			}
		).message;
		expect(message.metadata.trustedAgent.autoGenerated).toBeUndefined();
	});

	it("sets autoGenerated to true when explicitly passed", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "auto reply", DEFAULT_MESSAGE_SCOPE, {
			autoGenerated: true,
		});
		const message = (
			request.params as {
				message: { metadata: { trustedAgent: { autoGenerated?: boolean } } };
			}
		).message;
		expect(message.metadata.trustedAgent.autoGenerated).toBe(true);
	});

	it("does not set autoGenerated when passed as false", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "manual", DEFAULT_MESSAGE_SCOPE, {
			autoGenerated: false,
		});
		const message = (
			request.params as {
				message: { metadata: { trustedAgent: { autoGenerated?: boolean } } };
			}
		).message;
		expect(message.metadata.trustedAgent.autoGenerated).toBeUndefined();
	});
});
