import { describe, expect, it } from "vitest";
import { createEmptyPermissionState } from "../../../src/permissions/types.js";
import type { JsonRpcRequest, MessageSendParams } from "../../../src/protocol/types.js";
import {
	DEFAULT_MESSAGE_SCOPE,
	buildOutgoingMessageRequest,
} from "../../../src/runtime/message-conversations.js";
import type { Contact } from "../../../src/trust/types.js";

const CONTACT: Contact = {
	connectionId: "conn-test-001",
	peerAgentId: 42,
	peerChain: "eip155:8453",
	peerOwnerAddress: "0x1111111111111111111111111111111111111111",
	peerDisplayName: "TestPeer",
	peerAgentAddress: "0x2222222222222222222222222222222222222222",
	permissions: createEmptyPermissionState("2026-01-01T00:00:00.000Z"),
	establishedAt: "2026-01-01T00:00:00.000Z",
	lastContactAt: "2026-01-01T00:00:00.000Z",
	status: "active",
};

function getAutoGenerated(request: JsonRpcRequest): boolean | undefined {
	const params = request.params as MessageSendParams;
	return params.message.metadata?.trustedAgent?.autoGenerated;
}

describe("autoGenerated flag in outgoing messages", () => {
	it("does not set autoGenerated when not provided", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "hello");
		expect(getAutoGenerated(request)).toBeUndefined();
	});

	it("sets autoGenerated to true when explicitly passed", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "auto reply", DEFAULT_MESSAGE_SCOPE, {
			autoGenerated: true,
		});
		expect(getAutoGenerated(request)).toBe(true);
	});

	it("does not set autoGenerated when passed as false", () => {
		const request = buildOutgoingMessageRequest(CONTACT, "manual", DEFAULT_MESSAGE_SCOPE, {
			autoGenerated: false,
		});
		expect(getAutoGenerated(request)).toBeUndefined();
	});
});
