import { unlink } from "node:fs/promises";
import { normalizeGrantInput, isEthereumAddress } from "trusted-agents-core";
import {
	type TapHermesDaemonState,
	type TapHermesPaths,
	getTapHermesPaths,
	loadTapHermesPluginConfig,
	saveTapHermesDaemonState,
} from "./config.js";
import {
	type HermesTapError,
	HermesTapIpcServer,
	type HermesTapRequest,
	type HermesTapResponse,
} from "./ipc.js";
import { type HermesTapLogger, HermesTapRegistry } from "./registry.js";

const PARENT_WATCH_INTERVAL_MS = 5_000;

export interface StartTapHermesDaemonOptions {
	hermesHome?: string;
	gatewayPid: number;
	logger?: HermesTapLogger;
}

export class TapHermesDaemon {
	private readonly logger: HermesTapLogger;
	private readonly paths: TapHermesPaths;
	private readonly gatewayPid: number;
	private readonly server: HermesTapIpcServer;
	private readonly registryPromise: Promise<HermesTapRegistry>;
	private parentWatcher: NodeJS.Timeout | null = null;
	private stopping = false;

	constructor(options: StartTapHermesDaemonOptions) {
		this.logger = options.logger ?? console;
		this.gatewayPid = options.gatewayPid;
		this.paths = getTapHermesPaths(options.hermesHome);
		this.registryPromise = this.createRegistry();
		this.server = new HermesTapIpcServer(this.paths.socketPath, async (request) => await this.dispatch(request));
	}

	async start(): Promise<void> {
		const registry = await this.registryPromise;
		await registry.start();
		await this.server.start();
		await this.writeState();
		this.installParentWatcher();
	}

	async stop(): Promise<void> {
		if (this.stopping) {
			return;
		}
		this.stopping = true;
		if (this.parentWatcher) {
			clearInterval(this.parentWatcher);
			this.parentWatcher = null;
		}
		await this.server.stop().catch((error: unknown) => {
			this.logger.warn(`[trusted-agents-tap] Failed to stop IPC server: ${formatError(error)}`);
		});
		const registry = await this.registryPromise;
		await registry.stop().catch((error: unknown) => {
			this.logger.warn(`[trusted-agents-tap] Failed to stop TAP runtime registry: ${formatError(error)}`);
		});
		await unlink(this.paths.daemonStatePath).catch(() => {});
	}

	async runUntilStopped(): Promise<void> {
		await this.start();
		await new Promise<void>((resolve) => {
			const handleSignal = (signal: NodeJS.Signals) => {
				void this.stop().finally(() => {
					process.off("SIGINT", onSigint);
					process.off("SIGTERM", onSigterm);
					this.logger.info(`[trusted-agents-tap] Received ${signal}, shutting down`);
					resolve();
				});
			};
			const onSigint = () => {
				handleSignal("SIGINT");
			};
			const onSigterm = () => {
				handleSignal("SIGTERM");
			};
			process.on("SIGINT", onSigint);
			process.on("SIGTERM", onSigterm);
		});
	}

	private async createRegistry(): Promise<HermesTapRegistry> {
		const config = await loadTapHermesPluginConfig(this.paths.hermesHome);
		return new HermesTapRegistry(config, this.paths, this.logger);
	}

	private async dispatch(request: HermesTapRequest): Promise<HermesTapResponse> {
		try {
			const registry = await this.registryPromise;
			const params = isRecord(request.params) ? request.params : {};
			switch (request.method) {
				case "ping":
					return ok({ pong: true });
				case "status":
					return ok(await registry.status(optionalString(params.identity)));
				case "sync":
					return ok(await registry.sync(optionalString(params.identity)));
				case "restart":
					return ok(await registry.restart(optionalString(params.identity)));
				case "create_invite":
					return ok(
						await registry.createInvite(
							optionalString(params.identity),
							optionalNumber(params.expires_in_seconds),
						),
					);
				case "connect":
					return ok(
						await registry.connect({
							identity: optionalString(params.identity),
							inviteUrl: requireString(params.invite_url, "invite_url"),
						}),
					);
				case "send_message":
					return ok(
						await registry.sendMessage({
							identity: optionalString(params.identity),
							peer: requireString(params.peer, "peer"),
							text: requireString(params.text, "text"),
							scope: optionalString(params.scope),
							autoGenerated: optionalBoolean(params.auto_generated),
						}),
					);
				case "publish_grants":
					return ok(
						await registry.publishGrantSet({
							identity: optionalString(params.identity),
							peer: requireString(params.peer, "peer"),
							grantSet: normalizeGrantInput(params.grant_set),
							note: optionalString(params.note),
						}),
					);
				case "request_grants":
					return ok(
						await registry.requestGrantSet({
							identity: optionalString(params.identity),
							peer: requireString(params.peer, "peer"),
							grantSet: normalizeGrantInput(params.grant_set),
							note: optionalString(params.note),
						}),
					);
				case "request_funds":
					return ok(
						await registry.requestFunds({
							identity: optionalString(params.identity),
							peer: requireString(params.peer, "peer"),
							asset: requireAsset(params.asset),
							amount: requireString(params.amount, "amount"),
							chain: optionalString(params.chain),
							toAddress: optionalAddress(params.to_address),
							note: optionalString(params.note),
						}),
					);
				case "transfer":
					return ok(
						await registry.transfer({
							identity: optionalString(params.identity),
							asset: requireAsset(params.asset),
							amount: requireString(params.amount, "amount"),
							chain: optionalString(params.chain),
							toAddress: requireAddress(params.to_address, "to_address"),
						}),
					);
				case "request_meeting":
					return ok(
						await registry.requestMeeting({
							identity: optionalString(params.identity),
							peer: requireString(params.peer, "peer"),
							title: requireString(params.title, "title"),
							duration: optionalNumber(params.duration) ?? 60,
							preferred: optionalString(params.preferred),
							location: optionalString(params.location),
							note: optionalString(params.note),
						}),
					);
				case "respond_meeting":
					return ok(
						await registry.respondMeeting({
							identity: optionalString(params.identity),
							schedulingId: requireString(params.scheduling_id, "scheduling_id"),
							action: requireString(params.meeting_action, "meeting_action"),
							reason: optionalString(params.reason),
						}),
					);
				case "cancel_meeting":
					return ok(
						await registry.cancelMeeting({
							identity: optionalString(params.identity),
							schedulingId: requireString(params.scheduling_id, "scheduling_id"),
							reason: optionalString(params.reason),
						}),
					);
				case "list_pending":
					return ok(await registry.listPending(optionalString(params.identity)));
				case "resolve_pending":
					return ok(
						await registry.resolvePending({
							identity: optionalString(params.identity),
							requestId: requireString(params.request_id, "request_id"),
							approve: requireBoolean(params.approve, "approve"),
						}),
					);
				case "drain_notifications":
					return ok({ notifications: await registry.drainNotifications() });
				default:
					return fail({
						code: "UNKNOWN_METHOD",
						message: `Unsupported Hermes TAP method: ${request.method}`,
					});
			}
		} catch (error: unknown) {
			return fail({
				code: "DAEMON_ERROR",
				message: formatError(error),
			});
		}
	}

	private installParentWatcher(): void {
		if (this.parentWatcher) {
			clearInterval(this.parentWatcher);
		}
		this.parentWatcher = setInterval(() => {
			if (isProcessAlive(this.gatewayPid)) {
				return;
			}
			this.logger.info(
				`[trusted-agents-tap] Hermes gateway PID ${this.gatewayPid} is gone, stopping TAP daemon`,
			);
			void this.stop().finally(() => process.exit(0));
		}, PARENT_WATCH_INTERVAL_MS);
	}

	private async writeState(): Promise<void> {
		const registry = await this.registryPromise;
		const state: TapHermesDaemonState = {
			pid: process.pid,
			gatewayPid: this.gatewayPid,
			socketPath: this.paths.socketPath,
			startedAt: new Date().toISOString(),
			identities: registry.listConfiguredIdentities(),
		};
		await saveTapHermesDaemonState(this.paths.hermesHome, state);
	}
}

function ok(result: unknown): HermesTapResponse {
	return { ok: true, result };
}

function fail(error: HermesTapError): HermesTapResponse {
	return { ok: false, error };
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function optionalString(value: unknown): string | undefined {
	return typeof value === "string" && value.trim().length > 0 ? value.trim() : undefined;
}

function requireString(value: unknown, name: string): string {
	const normalized = optionalString(value);
	if (!normalized) {
		throw new Error(`${name} is required`);
	}
	return normalized;
}

function optionalNumber(value: unknown): number | undefined {
	return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function requireBoolean(value: unknown, name: string): boolean {
	if (typeof value !== "boolean") {
		throw new Error(`${name} is required`);
	}
	return value;
}

function optionalBoolean(value: unknown): boolean | undefined {
	return typeof value === "boolean" ? value : undefined;
}

function requireAsset(value: unknown): "native" | "usdc" {
	if (value === "native" || value === "usdc") {
		return value;
	}
	throw new Error("asset must be \"native\" or \"usdc\"");
}

function requireAddress(value: unknown, name: string): `0x${string}` {
	if (typeof value !== "string" || value.trim().length === 0) {
		throw new Error(`${name} is required`);
	}
	if (!isEthereumAddress(value)) {
		throw new Error(`Invalid Ethereum address: ${value}`);
	}
	return value as `0x${string}`;
}

function optionalAddress(value: unknown): `0x${string}` | undefined {
	if (value === undefined || value === null || value === "") {
		return undefined;
	}
	if (typeof value !== "string" || !isEthereumAddress(value)) {
		throw new Error(`Invalid Ethereum address: ${String(value)}`);
	}
	return value as `0x${string}`;
}

function isProcessAlive(pid: number): boolean {
	try {
		process.kill(pid, 0);
		return true;
	} catch {
		return false;
	}
}

function formatError(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}
