export interface TapEmitEventPayload {
	direction: string;
	from: number;
	fromName?: string;
	method: string;
	id: string | number;
	receipt_status: string;
	scope?: string;
	messageText?: string;
	autoGenerated?: boolean;
	[key: string]: unknown;
}

export type TapEventBucket = "auto-handle" | "escalate" | "notify";

export function classifyTapEvent(event: TapEmitEventPayload): TapEventBucket | null {
	if (event.direction !== "incoming") return null;
	if (event.receipt_status === "duplicate") return null;

	switch (event.method) {
		case "message/send":
		case "action/result":
		case "permissions/update":
			return "auto-handle";

		case "connection/request":
			return "escalate";

		case "action/request":
			if (event.scope === "scheduling/request") {
				return event.receipt_status === "queued" ? "escalate" : "auto-handle";
			}
			return event.receipt_status === "received" ? "auto-handle" : null;

		case "connection/result":
			return "notify";

		default:
			return null;
	}
}
