import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { TapEvent } from "trusted-agents-core";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { socketFilePath } from "../../src/config.js";
import { Daemon } from "../../src/daemon.js";

/**
 * Client compatibility regression gate for Cluster B (F4.3 / F5.3 / F5.4).
 *
 * This file stands up a real `Daemon` with a stubbed `TapMessagingService` and
 * posts the EXACT JSON bodies that the Hermes Python plugin
 * (`packages/cli/assets/hermes/plugin/client.py`) and the OpenClaw TS plugin
 * (`packages/openclaw-plugin/src/tapd-client.ts`) emit in production. It
 * asserts that tapd accepts every body shape and forwards the expected
 * arguments to the underlying service.
 *
 * If either host client drifts away from what tapd accepts, or if a future
 * route refactor re-breaks one of these shapes, this test fails loudly.
 * Update BOTH the client and this fixture in lock-step — do NOT "loosen" the
 * fixture to make it pass without also updating the matching client file.
 */

function makeFakeService() {
	return {
		hooks: {} as {
			onTypedEvent?: (event: TapEvent) => void;
		},
		start: vi.fn(async () => {}),
		stop: vi.fn(async () => {}),
		getStatus: vi.fn(async () => ({ running: true, lock: null, pendingRequests: [] })),
		resolvePending: vi.fn(async () => ({})),
		syncOnce: vi.fn(async () => ({
			synced: true,
			processed: 0,
			pendingRequests: [],
			pendingDeliveries: [],
		})),
		sendMessage: vi.fn(
			async (
				peer: string,
				_text: string,
				scope?: string,
				_options?: { autoGenerated?: boolean },
			) => ({
				receipt: { messageId: "msg-1", status: "delivered" },
				peerName: peer,
				peerAgentId: 99,
				scope: scope ?? "general-chat",
			}),
		),
		requestMeeting: vi.fn(
			async (input: {
				peer: string;
				proposal: {
					type: string;
					schedulingId: string;
					title: string;
					duration: number;
					slots: Array<{ start: string; end: string }>;
					originTimezone: string;
					location?: string;
					note?: string;
				};
			}) => ({
				receipt: { messageId: "msg-m", status: "delivered" },
				schedulingId: input.proposal.schedulingId,
				peerName: input.peer,
				peerAgentId: 99,
				title: input.proposal.title,
				duration: input.proposal.duration,
				slotCount: input.proposal.slots.length,
			}),
		),
		cancelMeeting: vi.fn(async (schedulingId: string) => ({
			requestId: "req-m",
			peerAgentId: 99,
			schedulingId,
			report: { synced: true, processed: 1, pendingRequests: [], pendingDeliveries: [] },
		})),
		listPendingRequests: vi.fn(async () => []),
		connect: vi.fn(async (params: { inviteUrl: string; waitMs?: number }) => ({
			connectionId: "conn-1",
			peerName: "Alice",
			peerAgentId: 99,
			status: params.waitMs === 0 ? "pending" : "active",
			receipt: { messageId: "msg-1", status: "delivered" },
		})),
		requestFunds: vi.fn(
			async (input: {
				peer: string;
				asset: string;
				amount: string;
				chain: string;
				toAddress: string;
			}) => ({
				receipt: { messageId: "msg-1", status: "delivered" },
				actionId: "act-1",
				peerName: input.peer,
				peerAgentId: 99,
				asset: input.asset,
				amount: input.amount,
				chain: input.chain,
				toAddress: input.toAddress,
			}),
		),
	};
}

const fakeExecuteTransfer = vi.fn(async () => ({
	txHash: "0xabc" as `0x${string}`,
}));

describe("tapd client compatibility (Hermes + OpenClaw)", () => {
	let dataDir: string;
	let daemon: Daemon | null = null;
	let port = 0;
	let token = "";
	let service: ReturnType<typeof makeFakeService>;

	beforeEach(async () => {
		dataDir = await mkdtemp(join(tmpdir(), "tapd-compat-"));
		service = makeFakeService();
		daemon = new Daemon({
			config: {
				dataDir,
				socketPath: socketFilePath(dataDir),
				tcpHost: "127.0.0.1",
				tcpPort: 0,
				ringBufferSize: 100,
			},
			identityAgentId: 42,
			identitySource: () => ({
				agentId: 42,
				chain: "eip155:8453",
				address: "0xabc",
				displayName: "Alice",
				dataDir,
			}),
			buildService: async () => service as never,
			trustStore: { getContacts: async () => [], getContact: async () => null } as never,
			conversationLogger: {
				logMessage: async () => {},
				getConversation: async () => null,
				listConversations: async () => [],
				generateTranscript: async () => "",
				markRead: async () => {},
			} as never,
			executeTransfer: fakeExecuteTransfer,
		});
		fakeExecuteTransfer.mockClear();
		await daemon.start();
		port = daemon.boundTcpPort();
		token = daemon.authToken();
	});

	afterEach(async () => {
		if (daemon) {
			await daemon.stop().catch(() => {});
			daemon = null;
		}
		await rm(dataDir, { recursive: true, force: true });
	});

	const post = async (path: string, body: unknown) =>
		fetch(`http://127.0.0.1:${port}${path}`, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${token}`,
				"Content-Type": "application/json",
			},
			body: JSON.stringify(body),
		});

	// -----------------------------------------------------------------------
	// Hermes Python client (packages/cli/assets/hermes/plugin/client.py)
	// -----------------------------------------------------------------------
	//
	// These bodies match the objects that `send_request` builds from the
	// `tap_gateway` params dict. Mirror the client.py `if action == "..."`
	// branches. If a branch changes, update the fixture here too.
	// -----------------------------------------------------------------------

	describe("Hermes Python client", () => {
		it("send_message with autoGenerated=true is forwarded to service.sendMessage", async () => {
			// client.py send_message action builds this exact body.
			const body = {
				peer: "Alice",
				text: "hello from hermes",
				scope: "general-chat",
				autoGenerated: true,
			};

			const response = await post("/api/messages", body);
			expect(response.status).toBe(200);
			expect(service.sendMessage).toHaveBeenCalledOnce();
			expect(service.sendMessage.mock.calls[0]).toEqual([
				"Alice",
				"hello from hermes",
				"general-chat",
				{ autoGenerated: true },
			]);
		});

		it("send_message without autoGenerated omits the options bag", async () => {
			const body = { peer: "Alice", text: "plain hi", scope: "general-chat" };

			const response = await post("/api/messages", body);
			expect(response.status).toBe(200);
			expect(service.sendMessage.mock.calls[0]?.[3]).toBeUndefined();
		});

		it("request_meeting (flat body) is accepted and forwards a built proposal", async () => {
			// client.py request_meeting action builds this exact flat body.
			// tapd constructs the full SchedulingProposal internally.
			const body = {
				peer: "Alice",
				title: "Pairing session",
				duration: 45,
				preferred: "2027-02-01T15:00:00.000Z",
				location: "Zoom",
				note: "bring the diagram",
			};

			const response = await post("/api/meetings", body);
			expect(response.status).toBe(200);
			expect(service.requestMeeting).toHaveBeenCalledOnce();

			const arg = service.requestMeeting.mock.calls[0]?.[0] as {
				peer: string;
				proposal: Record<string, unknown>;
			};
			expect(arg.peer).toBe("Alice");
			expect(arg.proposal.type).toBe("scheduling/propose");
			expect(typeof arg.proposal.schedulingId).toBe("string");
			expect(arg.proposal.title).toBe("Pairing session");
			expect(arg.proposal.duration).toBe(45);
			expect(arg.proposal.location).toBe("Zoom");
			expect(arg.proposal.note).toBe("bring the diagram");
			expect(Array.isArray(arg.proposal.slots)).toBe(true);
			expect((arg.proposal.slots as unknown[]).length).toBeGreaterThanOrEqual(1);
			expect(typeof arg.proposal.originTimezone).toBe("string");
		});

		it("request_meeting with only required fields also works", async () => {
			// client.py only sends the fields whose params are non-None.
			// Most-minimal body: peer, title, duration.
			const body = { peer: "Alice", title: "Quick sync", duration: 30 };

			const response = await post("/api/meetings", body);
			expect(response.status).toBe(200);
			expect(service.requestMeeting).toHaveBeenCalledOnce();
		});

		it("request_funds is accepted with chain and toAddress fields", async () => {
			// client.py request_funds action builds this exact body.
			const body = {
				peer: "Alice",
				asset: "usdc",
				amount: "1.50",
				chain: "eip155:8453",
				toAddress: "0x0000000000000000000000000000000000000000",
				note: "lunch",
			};

			const response = await post("/api/funds-requests", body);
			expect(response.status).toBe(200);
			expect(service.requestFunds).toHaveBeenCalledOnce();
		});

		it("transfer is accepted with chain and toAddress fields", async () => {
			// client.py transfer action builds this exact body.
			const body = {
				asset: "usdc",
				amount: "1.50",
				chain: "eip155:8453",
				toAddress: "0x0000000000000000000000000000000000000000",
			};

			const response = await post("/api/transfers", body);
			expect(response.status).toBe(200);
			expect(fakeExecuteTransfer).toHaveBeenCalledOnce();
		});

		it("connect is accepted with inviteUrl and waitMs", async () => {
			const body = { inviteUrl: "tap://invite/abc", waitMs: 1000 };
			const response = await post("/api/connect", body);
			expect(response.status).toBe(200);
			expect(service.connect).toHaveBeenCalledOnce();
		});
	});

	// -----------------------------------------------------------------------
	// OpenClaw TS client (packages/openclaw-plugin/src/tapd-client.ts)
	// -----------------------------------------------------------------------
	//
	// The OpenClaw client passes the tool params through to tapd unchanged.
	// These fixtures mirror the exact `client.*` method calls in
	// `packages/openclaw-plugin/src/tool.ts` — if a case there changes, fix
	// both places at once.
	// -----------------------------------------------------------------------

	describe("OpenClaw TS client", () => {
		it("sendMessage with autoGenerated=true is forwarded to service.sendMessage", async () => {
			// openclaw-plugin/src/tapd-client.ts sendMessage() POSTs the input
			// as-is to /api/messages.
			const body = {
				peer: "Bob",
				text: "hello from openclaw",
				scope: "default",
				autoGenerated: true,
			};

			const response = await post("/api/messages", body);
			expect(response.status).toBe(200);
			expect(service.sendMessage.mock.calls[0]).toEqual([
				"Bob",
				"hello from openclaw",
				"default",
				{ autoGenerated: true },
			]);
		});

		it("requestMeeting sends the flat shape from the tool layer", async () => {
			// tool.ts case "request_meeting" builds this exact flat object and
			// hands it to client.requestMeeting, which POSTs as-is.
			const body = {
				peer: "Bob",
				title: "Review",
				duration: 60,
				preferred: "2027-03-15T14:00:00.000Z",
				location: "Conf room A",
				note: "bring laptop",
			};

			const response = await post("/api/meetings", body);
			expect(response.status).toBe(200);
			expect(service.requestMeeting).toHaveBeenCalledOnce();

			const arg = service.requestMeeting.mock.calls[0]?.[0] as {
				peer: string;
				proposal: Record<string, unknown>;
			};
			expect(arg.peer).toBe("Bob");
			expect(arg.proposal.type).toBe("scheduling/propose");
			expect(arg.proposal.title).toBe("Review");
			expect(arg.proposal.duration).toBe(60);
			expect(arg.proposal.location).toBe("Conf room A");
			expect(arg.proposal.note).toBe("bring laptop");
		});

		it("requestMeeting without a preferred time still works", async () => {
			// Minimal body — tool.ts always passes duration, but preferred is
			// optional. The flat route should build a placeholder slot.
			const body = { peer: "Bob", title: "Standup", duration: 30 };

			const response = await post("/api/meetings", body);
			expect(response.status).toBe(200);
			const arg = service.requestMeeting.mock.calls[0]?.[0] as {
				proposal: { slots: Array<{ start: string; end: string }> };
			};
			expect(arg.proposal.slots).toHaveLength(1);
		});

		it("transfer posts { asset, amount, chain, toAddress } and hits the executor", async () => {
			const body = {
				asset: "usdc",
				amount: "2.00",
				chain: "eip155:8453",
				toAddress: "0x0000000000000000000000000000000000000000",
			};

			const response = await post("/api/transfers", body);
			expect(response.status).toBe(200);
			expect(fakeExecuteTransfer).toHaveBeenCalledOnce();
		});

		it("requestFunds posts { peer, asset, amount, chain, toAddress } and forwards", async () => {
			const body = {
				peer: "Bob",
				asset: "usdc",
				amount: "5.00",
				chain: "eip155:8453",
				toAddress: "0x0000000000000000000000000000000000000000",
				note: "rent split",
			};

			const response = await post("/api/funds-requests", body);
			expect(response.status).toBe(200);
			expect(service.requestFunds).toHaveBeenCalledOnce();
		});

		it("connect posts { inviteUrl } and forwards", async () => {
			const body = { inviteUrl: "tap://invite/xyz" };
			const response = await post("/api/connect", body);
			expect(response.status).toBe(200);
			expect(service.connect).toHaveBeenCalledOnce();
		});
	});
});
