import { randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AsyncMutex, nowISO, resolveDataDir } from "../common/index.js";
import type { PermissionGrantSet } from "../permissions/types.js";
import type {
	TapConnectResult,
	TapPublishGrantSetResult,
	TapRequestFundsInput,
	TapRequestFundsResult,
	TapRequestGrantSetResult,
	TapRequestMeetingInput,
	TapRequestMeetingResult,
	TapSendMessageResult,
} from "./service.js";

export type TapCommandJobType =
	| "connect"
	| "send-message"
	| "publish-grant-set"
	| "request-grant-set"
	| "request-funds"
	| "request-meeting";

interface TapCommandJobBase<TType extends TapCommandJobType, TPayload> {
	jobId: string;
	type: TType;
	createdAt: string;
	requestedBy?: string;
	payload: TPayload;
}

interface TapConnectJob
	extends TapCommandJobBase<
		"connect",
		{
			inviteUrl: string;
		}
	> {}

interface TapSendMessageJob
	extends TapCommandJobBase<
		"send-message",
		{
			peer: string;
			text: string;
			scope: string;
			autoGenerated?: boolean;
		}
	> {}

interface TapPublishGrantSetJob
	extends TapCommandJobBase<
		"publish-grant-set",
		{
			peer: string;
			grantSet: PermissionGrantSet;
			note?: string;
		}
	> {}

interface TapRequestGrantSetJob
	extends TapCommandJobBase<
		"request-grant-set",
		{
			peer: string;
			grantSet: PermissionGrantSet;
			note?: string;
		}
	> {}

interface TapRequestFundsJob
	extends TapCommandJobBase<
		"request-funds",
		{
			input: TapRequestFundsInput;
		}
	> {}

interface TapRequestMeetingJob
	extends TapCommandJobBase<
		"request-meeting",
		{
			input: TapRequestMeetingInput;
		}
	> {}

export type TapCommandJob =
	| TapConnectJob
	| TapSendMessageJob
	| TapPublishGrantSetJob
	| TapRequestGrantSetJob
	| TapRequestFundsJob
	| TapRequestMeetingJob;

export type ProcessingTapCommandJob<TJob extends TapCommandJob = TapCommandJob> = TJob & {
	claimedAt: string;
	claimedBy: string;
	claimedByPid: number;
};

export type TapCommandJobResultPayload =
	| TapConnectResult
	| TapSendMessageResult
	| TapPublishGrantSetResult
	| TapRequestGrantSetResult
	| TapRequestFundsResult
	| TapRequestMeetingResult;

export interface TapCommandJobResult {
	jobId: string;
	type: TapCommandJobType;
	finishedAt: string;
	status: "completed" | "failed";
	result?: TapCommandJobResultPayload;
	error?: string;
	errorCode?: string;
}

export interface ClaimNextJobOptions {
	owner: string;
	staleLeaseMs: number;
}

export interface RecoverOutboxOptions {
	staleLeaseMs: number;
}

export interface TapCommandOutboxStats {
	queued: number;
	processing: number;
	results: number;
}

export class FileTapCommandOutbox {
	private readonly queuedDir: string;
	private readonly processingDir: string;
	private readonly resultsDir: string;
	private readonly writeMutex = new AsyncMutex();

	constructor(dataDir = join(process.env.HOME ?? "~", ".trustedagents")) {
		const resolvedDataDir = resolveDataDir(dataDir);
		const outboxDir = join(resolvedDataDir, "outbox");
		this.queuedDir = join(outboxDir, "queued");
		this.processingDir = join(outboxDir, "processing");
		this.resultsDir = join(outboxDir, "results");
	}

	async enqueue(
		job: Omit<TapCommandJob, "jobId" | "createdAt"> & { jobId?: string; createdAt?: string },
	): Promise<TapCommandJob> {
		return await this.writeMutex.runExclusive(async () => {
			await this.ensureDirs();
			const jobId = job.jobId ?? createQueuedJobId();
			const created = {
				...job,
				jobId,
				createdAt: job.createdAt ?? nowISO(),
			} as TapCommandJob;
			await this.writeJsonAtomic(this.queuedPath(jobId), created);
			return created;
		});
	}

	async claimNext(options: ClaimNextJobOptions): Promise<ProcessingTapCommandJob | null> {
		return await this.writeMutex.runExclusive(async () => {
			await this.ensureDirs();
			await this.recoverStaleProcessingUnsafe(options);
			const names = await this.listJsonFiles(this.queuedDir);
			for (const name of names) {
				const jobId = filenameToJobId(name);
				const source = this.queuedPath(jobId);
				const target = this.processingPath(jobId);
				try {
					await rename(source, target);
				} catch (error: unknown) {
					const code =
						error instanceof Error && "code" in error
							? (error as NodeJS.ErrnoException).code
							: undefined;
					if (code === "ENOENT") {
						continue;
					}
					throw error;
				}

				const queued = (await this.readJson(target)) as TapCommandJob;
				const claimed: ProcessingTapCommandJob = {
					...queued,
					claimedAt: nowISO(),
					claimedBy: options.owner,
					claimedByPid: process.pid,
				};
				await this.writeJsonAtomic(target, claimed);
				return claimed;
			}
			return null;
		});
	}

	async complete(job: ProcessingTapCommandJob, result: TapCommandJobResultPayload): Promise<void> {
		await this.writeMutex.runExclusive(async () => {
			await this.ensureDirs();
			await this.writeJsonAtomic(this.resultPath(job.jobId), {
				jobId: job.jobId,
				type: job.type,
				finishedAt: nowISO(),
				status: "completed",
				result,
			} satisfies TapCommandJobResult);
			await rm(this.processingPath(job.jobId), { force: true });
		});
	}

	async fail(job: ProcessingTapCommandJob, error: string, errorCode?: string): Promise<void> {
		await this.writeMutex.runExclusive(async () => {
			await this.ensureDirs();
			await this.writeJsonAtomic(this.resultPath(job.jobId), {
				jobId: job.jobId,
				type: job.type,
				finishedAt: nowISO(),
				status: "failed",
				error,
				errorCode,
			} satisfies TapCommandJobResult);
			await rm(this.processingPath(job.jobId), { force: true });
		});
	}

	async getResult(jobId: string): Promise<TapCommandJobResult | null> {
		try {
			return (await this.readJson(this.resultPath(jobId))) as TapCommandJobResult;
		} catch (error: unknown) {
			const code =
				error instanceof Error && "code" in error
					? (error as NodeJS.ErrnoException).code
					: undefined;
			if (code === "ENOENT") {
				return null;
			}
			throw error;
		}
	}

	async getQueuedJob(jobId: string): Promise<TapCommandJob | null> {
		try {
			return (await this.readJson(this.queuedPath(jobId))) as TapCommandJob;
		} catch (error: unknown) {
			const code =
				error instanceof Error && "code" in error
					? (error as NodeJS.ErrnoException).code
					: undefined;
			if (code === "ENOENT") {
				return null;
			}
			throw error;
		}
	}

	async stats(): Promise<TapCommandOutboxStats> {
		await this.ensureDirs();
		const [queued, processing, results] = await Promise.all([
			this.listJsonFiles(this.queuedDir),
			this.listJsonFiles(this.processingDir),
			this.listJsonFiles(this.resultsDir),
		]);
		return {
			queued: queued.length,
			processing: processing.length,
			results: results.length,
		};
	}

	async cleanupResults(retentionMs: number): Promise<void> {
		await this.writeMutex.runExclusive(async () => {
			await this.ensureDirs();
			const cutoff = Date.now() - retentionMs;
			const names = await this.listJsonFiles(this.resultsDir);
			for (const name of names) {
				const path = join(this.resultsDir, name);
				const entryStat = await stat(path).catch(() => null);
				if (!entryStat || entryStat.mtimeMs > cutoff) {
					continue;
				}
				await rm(path, { force: true });
			}
		});
	}

	async recoverStaleProcessing(options: RecoverOutboxOptions): Promise<void> {
		await this.writeMutex.runExclusive(async () => {
			await this.recoverStaleProcessingUnsafe(options);
		});
	}

	private async ensureDirs(): Promise<void> {
		await mkdir(this.queuedDir, { recursive: true, mode: 0o700 });
		await mkdir(this.processingDir, { recursive: true, mode: 0o700 });
		await mkdir(this.resultsDir, { recursive: true, mode: 0o700 });
	}

	private async recoverStaleProcessingUnsafe(options: RecoverOutboxOptions): Promise<void> {
		await this.ensureDirs();
		const names = await this.listJsonFiles(this.processingDir);
		for (const name of names) {
			const path = join(this.processingDir, name);
			const processing = (await this.readJson(path)) as Partial<ProcessingTapCommandJob>;
			const claimedAt =
				typeof processing.claimedAt === "string" ? Date.parse(processing.claimedAt) : Number.NaN;
			if (!Number.isFinite(claimedAt)) {
				await rm(path, { force: true });
				continue;
			}
			if (Date.now() - claimedAt < options.staleLeaseMs) {
				continue;
			}
			if (
				typeof processing.claimedByPid === "number" &&
				processing.claimedByPid > 0 &&
				isProcessLikelyAlive(processing.claimedByPid)
			) {
				continue;
			}
			const queued = stripProcessingFields(processing);
			await this.writeJsonAtomic(this.queuedPath(queued.jobId), queued);
			await rm(path, { force: true });
		}
	}

	private queuedPath(jobId: string): string {
		return join(this.queuedDir, `${jobId}.json`);
	}

	private processingPath(jobId: string): string {
		return join(this.processingDir, `${jobId}.json`);
	}

	private resultPath(jobId: string): string {
		return join(this.resultsDir, `${jobId}.json`);
	}

	private async listJsonFiles(directory: string): Promise<string[]> {
		try {
			return (await readdir(directory)).filter((name) => name.endsWith(".json")).sort();
		} catch (error: unknown) {
			const code =
				error instanceof Error && "code" in error
					? (error as NodeJS.ErrnoException).code
					: undefined;
			if (code === "ENOENT") {
				return [];
			}
			throw error;
		}
	}

	private async readJson(path: string): Promise<unknown> {
		return JSON.parse(await readFile(path, "utf-8"));
	}

	private async writeJsonAtomic(path: string, value: unknown): Promise<void> {
		const tempPath = `${path}.${randomUUID()}.tmp`;
		await writeFile(tempPath, JSON.stringify(value, null, "\t"), {
			encoding: "utf-8",
			mode: 0o600,
		});
		await rename(tempPath, path);
	}
}

function filenameToJobId(name: string): string {
	return name.endsWith(".json") ? name.slice(0, -".json".length) : name;
}

let lastJobTimestamp = 0;
let lastJobSequence = 0;

function createQueuedJobId(): string {
	const now = Date.now();
	if (now === lastJobTimestamp) {
		lastJobSequence += 1;
	} else {
		lastJobTimestamp = now;
		lastJobSequence = 0;
	}
	return `${String(now).padStart(16, "0")}-${String(lastJobSequence).padStart(6, "0")}-${randomUUID()}`;
}

function stripProcessingFields(value: Partial<ProcessingTapCommandJob>): TapCommandJob {
	const {
		claimedAt: _claimedAt,
		claimedBy: _claimedBy,
		claimedByPid: _claimedByPid,
		...rest
	} = value;
	return rest as TapCommandJob;
}

function isProcessLikelyAlive(pid: number): boolean {
	if (!Number.isInteger(pid) || pid <= 0) {
		return false;
	}
	try {
		process.kill(pid, 0);
		return true;
	} catch (error: unknown) {
		const code =
			error instanceof Error && "code" in error ? (error as NodeJS.ErrnoException).code : undefined;
		return code === "EPERM";
	}
}
