import type { PermissionGrantSet } from "../permissions/types.js";
import type {
	TapConnectResult,
	TapPublishGrantSetResult,
	TapRequestFundsInput,
	TapRequestFundsResult,
	TapRequestGrantSetResult,
	TapRequestMeetingInput,
	TapRequestMeetingResult,
	TapSendMessageResult,
} from "./service.js";

export type TapCommandJobType =
	| "connect"
	| "send-message"
	| "publish-grant-set"
	| "request-grant-set"
	| "request-funds"
	| "request-meeting";

interface TapCommandJobBase<TType extends TapCommandJobType, TPayload> {
	jobId: string;
	type: TType;
	createdAt: string;
	requestedBy?: string;
	payload: TPayload;
}

interface TapConnectJob
	extends TapCommandJobBase<
		"connect",
		{
			inviteUrl: string;
		}
	> {}

interface TapSendMessageJob
	extends TapCommandJobBase<
		"send-message",
		{
			peer: string;
			text: string;
			scope: string;
			autoGenerated?: boolean;
		}
	> {}

interface TapPublishGrantSetJob
	extends TapCommandJobBase<
		"publish-grant-set",
		{
			peer: string;
			grantSet: PermissionGrantSet;
			note?: string;
		}
	> {}

interface TapRequestGrantSetJob
	extends TapCommandJobBase<
		"request-grant-set",
		{
			peer: string;
			grantSet: PermissionGrantSet;
			note?: string;
		}
	> {}

interface TapRequestFundsJob
	extends TapCommandJobBase<
		"request-funds",
		{
			input: TapRequestFundsInput;
		}
	> {}

interface TapRequestMeetingJob
	extends TapCommandJobBase<
		"request-meeting",
		{
			input: TapRequestMeetingInput;
		}
	> {}

export type TapCommandJob =
	| TapConnectJob
	| TapSendMessageJob
	| TapPublishGrantSetJob
	| TapRequestGrantSetJob
	| TapRequestFundsJob
	| TapRequestMeetingJob;

export type TapCommandJobIntent = TapCommandJob extends infer TJob
	? TJob extends TapCommandJob
		? Pick<TJob, "type" | "payload">
		: never
	: never;

export type TapCommandJobResultPayload =
	| TapConnectResult
	| TapSendMessageResult
	| TapPublishGrantSetResult
	| TapRequestGrantSetResult
	| TapRequestFundsResult
	| TapRequestMeetingResult;

export interface TapCommandJobResult {
	jobId: string;
	type: TapCommandJobType;
	finishedAt: string;
	status: "completed" | "failed";
	result?: TapCommandJobResultPayload;
	error?: string;
	errorCode?: string;
}
