import { execFile, execFileSync } from "node:child_process";
import { mkdir, mkdtemp, rm } from "node:fs/promises";
import net from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { installTapHermesAssets } from "../src/hermes/install.js";

const execFileAsync = promisify(execFile);

const PYTHON_BIN = (() => {
	if (process.env.PYTHON_BIN) return process.env.PYTHON_BIN;
	try {
		return execFileSync("which", ["python3"], { encoding: "utf-8" }).trim() || "python3";
	} catch {
		return "python3";
	}
})();

/**
 * After Phase 4 the Hermes Python plugin is a thin HTTP-over-Unix-socket
 * client of tapd. These tests stand up an in-process Unix socket HTTP
 * server that mimics tapd's responses for a few key endpoints, then run
 * the real Python plugin against it.
 */
describe("Hermes Python TAP bridge (HTTP-over-Unix-socket)", () => {
	let tempRoot: string;
	let dataDir: string;
	let hermesHome: string;
	let originalDataDir: string | undefined;
	let originalHermesHome: string | undefined;

	beforeEach(async () => {
		tempRoot = await mkdtemp(join(tmpdir(), "tap-hermes-py-"));
		dataDir = join(tempRoot, "data");
		hermesHome = join(tempRoot, "hermes-home");
		await mkdir(dataDir, { recursive: true });
		await mkdir(hermesHome, { recursive: true });
		originalDataDir = process.env.TAP_DATA_DIR;
		originalHermesHome = process.env.HERMES_HOME;
		process.env.TAP_DATA_DIR = dataDir;
		process.env.HERMES_HOME = hermesHome;
		await installTapHermesAssets(hermesHome);
	});

	afterEach(async () => {
		process.env.TAP_DATA_DIR = originalDataDir;
		process.env.HERMES_HOME = originalHermesHome;
		await rm(tempRoot, { recursive: true, force: true });
	});

	it("returns a clean error when tapd is not running and tap is not on PATH", async () => {
		const output = await runPluginExpression(
			'print(json.dumps(module.send_request("drain_notifications")))',
		);
		const parsed = JSON.parse(output) as { error?: string };
		expect(parsed.error).toBeDefined();
		expect(parsed.error).toContain("tapd is not running");
	});

	it("drains notifications via GET /api/notifications/drain", async () => {
		const server = await startFakeTapdServer(join(dataDir, ".tapd.sock"), {
			"GET /api/notifications/drain": {
				notifications: [
					{
						type: "escalation",
						oneLiner: "Connection request from Alice",
					},
				],
			},
		});
		try {
			const output = await runPluginExpression(
				"print(json.dumps(module.inject_tap_notifications()))",
			);
			const result = JSON.parse(output) as { context?: string };
			expect(result.context).toContain("[TAP Notifications]");
			expect(result.context).toContain("Connection request from Alice");
		} finally {
			await server.stop();
		}
	});

	it("forwards tap_gateway status to GET /daemon/health", async () => {
		const server = await startFakeTapdServer(join(dataDir, ".tapd.sock"), {
			"GET /daemon/health": { status: "ok", version: "test", uptime: 1, transportConnected: true },
		});
		try {
			const output = await runPluginExpression(
				'print(module.handle_tap_gateway({"action": "status"}))',
			);
			const result = JSON.parse(output) as { status?: string };
			expect(result.status).toBe("ok");
		} finally {
			await server.stop();
		}
	});

	it("forwards send_message to POST /api/messages", async () => {
		const requestSpy: { body?: string } = {};
		const server = await startFakeTapdServer(join(dataDir, ".tapd.sock"), {
			"POST /api/messages": (body) => {
				requestSpy.body = body;
				return { receipt: { messageId: "m-1", status: "delivered" } };
			},
		});
		try {
			const output = await runPluginExpression(
				'print(module.handle_tap_gateway({"action": "send_message", "peer": "Alice", "text": "hi"}))',
			);
			const result = JSON.parse(output) as { receipt?: { messageId: string } };
			expect(result.receipt?.messageId).toBe("m-1");
			expect(requestSpy.body).toBeDefined();
			expect(JSON.parse(requestSpy.body ?? "{}")).toEqual({ peer: "Alice", text: "hi" });
		} finally {
			await server.stop();
		}
	});

	it("forwards send_message with autoGenerated: true on the wire", async () => {
		const requestSpy: { body?: string } = {};
		const server = await startFakeTapdServer(join(dataDir, ".tapd.sock"), {
			"POST /api/messages": (body) => {
				requestSpy.body = body;
				return { receipt: { messageId: "m-2", status: "delivered" } };
			},
		});
		try {
			await runPluginExpression(
				'print(module.handle_tap_gateway({"action": "send_message", "peer": "Alice", "text": "auto", "auto_generated": True}))',
			);
			expect(requestSpy.body).toBeDefined();
			expect(JSON.parse(requestSpy.body ?? "{}")).toEqual({
				peer: "Alice",
				text: "auto",
				autoGenerated: true,
			});
		} finally {
			await server.stop();
		}
	});

	it("forwards request_meeting as the flat shape to POST /api/meetings", async () => {
		const requestSpy: { body?: string } = {};
		const server = await startFakeTapdServer(join(dataDir, ".tapd.sock"), {
			"POST /api/meetings": (body) => {
				requestSpy.body = body;
				return {
					receipt: { messageId: "m-3", status: "delivered" },
					schedulingId: "sch-x",
				};
			},
		});
		try {
			await runPluginExpression(
				'print(module.handle_tap_gateway({"action": "request_meeting", "peer": "Alice", "title": "Sync", "duration": 45, "preferred": "2027-06-15T09:00:00.000Z", "location": "Zoom", "note": "Bring numbers"}))',
			);
			expect(requestSpy.body).toBeDefined();
			const parsed = JSON.parse(requestSpy.body ?? "{}") as Record<string, unknown>;
			expect(parsed).toEqual({
				peer: "Alice",
				title: "Sync",
				duration: 45,
				preferred: "2027-06-15T09:00:00.000Z",
				location: "Zoom",
				note: "Bring numbers",
			});
			// No proposal wrapper — tapd builds the full SchedulingProposal.
			expect(parsed).not.toHaveProperty("proposal");
		} finally {
			await server.stop();
		}
	});

	it("skips notification context injection when no notifications render any lines", async () => {
		const output = await runPluginExpression(
			'print(json.dumps(module.format_notification_context([{"type": "summary", "oneLiner": "   "}])))',
		);
		expect(JSON.parse(output)).toBeNull();
	});
});

type FakeResponse = Record<string, unknown> | ((body: string) => Record<string, unknown>);

async function startFakeTapdServer(
	socketPath: string,
	routes: Record<string, FakeResponse>,
): Promise<{ stop: () => Promise<void> }> {
	const server = net.createServer((socket) => {
		let buf = "";
		socket.on("data", (chunk) => {
			buf += chunk.toString("utf-8");
			// Wait for end of headers
			const headerEnd = buf.indexOf("\r\n\r\n");
			if (headerEnd === -1) return;
			const headersBlock = buf.slice(0, headerEnd);
			const lines = headersBlock.split("\r\n");
			const [requestLine] = lines;
			const [method, path] = (requestLine ?? "").split(" ");
			const contentLengthHeader = lines.find((l) => l.toLowerCase().startsWith("content-length:"));
			const contentLength = contentLengthHeader
				? Number.parseInt(contentLengthHeader.split(":")[1]?.trim() ?? "0", 10)
				: 0;
			const bodyStart = headerEnd + 4;
			const haveBytes = Buffer.byteLength(buf.slice(bodyStart), "utf-8");
			if (haveBytes < contentLength) return;
			const body = buf.slice(bodyStart, bodyStart + contentLength);
			const key = `${method} ${path}`;
			const route = routes[key];
			if (route === undefined) {
				const notFoundBody = JSON.stringify({
					error: { code: "not_found", message: `no fake route for ${key}` },
				});
				socket.end(httpResponse(404, notFoundBody));
				return;
			}
			const payload: Record<string, unknown> = typeof route === "function" ? route(body) : route;
			socket.end(httpResponse(200, JSON.stringify(payload)));
		});
	});

	await new Promise<void>((resolve, reject) => {
		server.once("error", reject);
		server.listen(socketPath, () => resolve());
	});

	return {
		stop: () =>
			new Promise<void>((resolve, reject) =>
				server.close((err) => (err ? reject(err) : resolve())),
			),
	};
}

function httpResponse(status: number, body: string): string {
	const reason = status === 200 ? "OK" : status === 404 ? "Not Found" : "Error";
	const length = Buffer.byteLength(body, "utf-8");
	return [
		`HTTP/1.1 ${status} ${reason}`,
		"Content-Type: application/json",
		`Content-Length: ${length}`,
		"Connection: close",
		"",
		body,
	].join("\r\n");
}

async function runPluginExpression(expression: string): Promise<string> {
	const script = `
import importlib.util
import json
import os
import sys
from pathlib import Path

plugin_dir = Path(os.environ["HERMES_HOME"]) / "plugins" / "trusted-agents-tap"
init_path = plugin_dir / "__init__.py"
spec = importlib.util.spec_from_file_location(
    "trusted_agents_tap",
    init_path,
    submodule_search_locations=[str(plugin_dir)],
)
module = importlib.util.module_from_spec(spec)
sys.modules["trusted_agents_tap"] = module
spec.loader.exec_module(module)
${expression}
`.trim();

	const env: Record<string, string> = {};
	for (const [k, v] of Object.entries(process.env)) {
		if (typeof v === "string") env[k] = v;
	}
	// Force `tap` binary lookup to fail so the unhealthy-path test is
	// deterministic. Note the python interpreter is invoked by absolute path
	// so PATH stubbing doesn't affect spawn().
	env.PATH = "/nonexistent";

	const result = await execFileAsync(PYTHON_BIN, ["-c", script], { env, encoding: "utf8" });
	return result.stdout.trim();
}
