import { describe, expect, it, vi } from "vitest";
import type { OpenClawTapdClient } from "../src/tapd-client.js";
import { createTapGatewayTool } from "../src/tool.js";

function makeClient(overrides: Partial<Record<keyof OpenClawTapdClient, unknown>> = {}) {
	const base = {
		health: vi.fn(async () => ({ status: "ok" })),
		drainNotifications: vi.fn(async () => ({ notifications: [] })),
		sendMessage: vi.fn(async () => ({ ok: true })),
		connect: vi.fn(async () => ({ ok: true })),
		transfer: vi.fn(async () => ({ ok: true, txHash: "0xabc" })),
		requestFunds: vi.fn(async () => ({ ok: true })),
		publishGrants: vi.fn(async () => ({ ok: true })),
		requestGrants: vi.fn(async () => ({ ok: true })),
		requestMeeting: vi.fn(async () => ({ ok: true })),
		respondMeeting: vi.fn(async () => ({ ok: true })),
		cancelMeeting: vi.fn(async () => ({ ok: true })),
		listPending: vi.fn(async () => []),
		resolvePending: vi.fn(async () => ({ resolved: true })),
		createInvite: vi.fn(async () => ({ url: "tap://invite" })),
		sync: vi.fn(async () => ({ ok: true })),
		shutdown: vi.fn(async () => ({ ok: true })),
	};
	return Object.assign(base, overrides) as unknown as OpenClawTapdClient & typeof base;
}

describe("createTapGatewayTool", () => {
	it("returns JSON results for the status action and calls health()", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		const result = await tool.execute?.("call-1", { action: "status" });

		expect(client.health).toHaveBeenCalledTimes(1);
		expect(result?.details).toEqual({ status: "ok" });
	});

	it("dispatches each high-level action to the matching client method", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await tool.execute?.("c", { action: "sync" });
		expect(client.sync).toHaveBeenCalled();

		await tool.execute?.("c", { action: "create_invite", expiresInSeconds: 600 });
		expect(client.createInvite).toHaveBeenCalledWith({ expiresInSeconds: 600 });

		await tool.execute?.("c", { action: "connect", inviteUrl: "tap://invite" });
		expect(client.connect).toHaveBeenCalledWith({ inviteUrl: "tap://invite" });

		await tool.execute?.("c", {
			action: "send_message",
			peer: "alice",
			text: "hi",
			scope: "default",
			autoGenerated: true,
		});
		expect(client.sendMessage).toHaveBeenCalledWith({
			peer: "alice",
			text: "hi",
			scope: "default",
			autoGenerated: true,
		});

		await tool.execute?.("c", { action: "list_pending" });
		expect(client.listPending).toHaveBeenCalled();
	});

	it("refuses action=restart with a pointer to the CLI supervisor command", async () => {
		// Thin plugins can't respawn tapd; a bare shutdown-as-restart was a
		// silent outage. The action must now fail loudly with operator
		// guidance rather than dispatching to client.shutdown().
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(tool.execute?.("c", { action: "restart" })).rejects.toThrow(/tap daemon restart/);
		expect(client.shutdown).not.toHaveBeenCalled();
	});

	it("requires inviteUrl for the connect action", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(tool.execute?.("c", { action: "connect" })).rejects.toThrow(
			"inviteUrl is required",
		);
		expect(client.connect).not.toHaveBeenCalled();
	});

	it("requires peer + text for send_message", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(tool.execute?.("c", { action: "send_message" })).rejects.toThrow(
			"peer is required",
		);
		await expect(tool.execute?.("c", { action: "send_message", peer: "alice" })).rejects.toThrow(
			"text is required",
		);
	});

	it("rejects non-numeric and non-positive transfer amounts", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(
			tool.execute?.("c", {
				action: "transfer",
				asset: "usdc",
				amount: "abc",
				toAddress: "0x1111111111111111111111111111111111111111",
			}),
		).rejects.toThrow("amount must be a positive number");

		await expect(
			tool.execute?.("c", {
				action: "transfer",
				asset: "usdc",
				amount: "-1",
				toAddress: "0x1111111111111111111111111111111111111111",
			}),
		).rejects.toThrow("amount must be a positive number");

		expect(client.transfer).not.toHaveBeenCalled();
	});

	it("rejects malformed Ethereum addresses on transfer", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(
			tool.execute?.("c", {
				action: "transfer",
				asset: "usdc",
				amount: "0.5",
				toAddress: "not-an-address",
			}),
		).rejects.toThrow("Invalid Ethereum address");
	});

	it("forwards a well-formed transfer to the client", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await tool.execute?.("c", {
			action: "transfer",
			asset: "usdc",
			amount: "0.5",
			chain: "eip155:8453",
			toAddress: "0x1111111111111111111111111111111111111111",
		});

		expect(client.transfer).toHaveBeenCalledWith({
			asset: "usdc",
			amount: "0.5",
			chain: "eip155:8453",
			toAddress: "0x1111111111111111111111111111111111111111",
		});
	});

	it("maps respond_meeting accept/reject to approve booleans", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await tool.execute?.("c", {
			action: "respond_meeting",
			schedulingId: "s-1",
			meetingAction: "accept",
		});
		expect(client.respondMeeting).toHaveBeenCalledWith("s-1", {
			approve: true,
			reason: undefined,
		});

		await tool.execute?.("c", {
			action: "respond_meeting",
			schedulingId: "s-2",
			meetingAction: "reject",
			reason: "later",
		});
		expect(client.respondMeeting).toHaveBeenCalledWith("s-2", {
			approve: false,
			reason: "later",
		});
	});

	it("requires a meetingAction value for respond_meeting", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await expect(
			tool.execute?.("c", { action: "respond_meeting", schedulingId: "s-1" }),
		).rejects.toThrow("meetingAction is required");
	});

	it("routes resolve_pending approve/deny correctly", async () => {
		const client = makeClient();
		const tool = createTapGatewayTool(client);

		await tool.execute?.("c", {
			action: "resolve_pending",
			requestId: "r-1",
			approve: true,
			note: "ok",
		});
		expect(client.resolvePending).toHaveBeenCalledWith("r-1", true, {
			note: "ok",
			reason: undefined,
		});

		await tool.execute?.("c", {
			action: "resolve_pending",
			requestId: "r-2",
			approve: false,
			reason: "no",
		});
		expect(client.resolvePending).toHaveBeenCalledWith("r-2", false, {
			note: undefined,
			reason: "no",
		});
	});
});
