import type { InviteData } from "../connection/types.js";
import type { PermissionGrantSet } from "../permissions/types.js";

export type JsonRpcId = string | number | null;

export interface JsonRpcRequest {
	jsonrpc: "2.0";
	method: string;
	id: JsonRpcId;
	params?: unknown;
}

export interface JsonRpcResponse {
	jsonrpc: "2.0";
	id: JsonRpcId;
	result?: unknown;
	error?: JsonRpcErrorObject;
}

export interface JsonRpcErrorObject {
	code: number;
	message: string;
	data?: unknown;
}

export interface TextPart {
	kind: "text";
	text: string;
}

export interface DataPart {
	kind: "data";
	data: Record<string, unknown>;
}

export type MessagePart = TextPart | DataPart;

export interface TrustedAgentMetadata {
	connectionId: string;
	conversationId: string;
	scope: string;
	requiresHumanApproval: boolean;
	autoGenerated?: boolean;
}

export interface Message {
	messageId: string;
	role: "user" | "agent";
	parts: MessagePart[];
	metadata?: {
		trustedAgent?: TrustedAgentMetadata;
	};
}

export interface AgentIdentifier {
	agentId: number;
	chain: string;
	ownerAddress?: `0x${string}`;
}

export interface ConnectionRequestParams {
	from: AgentIdentifier;
	invite: InviteData;
	timestamp: string;
}

export interface ConnectionResultParams {
	requestId: string;
	from: AgentIdentifier;
	status: "accepted" | "rejected";
	reason?: string;
	timestamp: string;
}

export interface MessageSendParams {
	message: Message;
}

export interface PermissionsUpdateParams {
	grantSet: PermissionGrantSet;
	grantor: AgentIdentifier;
	grantee: AgentIdentifier;
	note?: string;
	timestamp: string;
}
